import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import Navbar from "@/component/layout/Navbar";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/Providers";
import Footer from "@/component/layout/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}>
        {/* navbar */}
        <Providers>
          <Navbar />
          <main>{children}</main>
          <Toaster position="top-center" richColors />
        </Providers>

        {/* footer */}
        <Footer />
      </body>
    </html>
  );
}
